// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qwiqapp.demo.repository;

import com.qwiqapp.demo.repository.UsersRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsersRepository_Roo_Jpa_Repository {
    
    declare @type: UsersRepository: @Transactional(readOnly = true);
    
}
