#spring:
#  profiles:
#    active:
#    - 

 spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/qwiqapp
    username: one24apps
    password: geekspace
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      